USE anagraf INDEX codistr
ZAP 
USE arkivio INDEX articolo
ZAP 
USE carichi INDEX procar
ZAP  
USE arkivold INDEX prodold
ZAP 
USE arkivio INDEX prodo,articolo
ZAP 
USE arkivold INDEX prodold
ZAP 
USE carichi INDEX procar
ZAP
USE progcar INDEX codpro 
ZAP
USE scarichi INDEX ndxscari 
ZAP
USE arkivio INDEX articolo  
ZAP
USE valcar 
ZAP
USE valcar2 
ZAP
USE valcar3 
ZAP
USE scarichi INDEX ndxscari 
ZAP
USE arkivio  
ZAP
USE arkivold  
ZAP
